### ISSUE TITLE
Always renders Version 7

### ISSUE THREAD

**Issue by PhilShaw852** [yoprogramo/QRcodeDisplay#5]
Even if I change the version from 7 to 2, the QR image renders as Version 7.

**Comment by yoprogramo** [comment]
Hello,

Yes it is fixed to level 7 due to memory restrictions. You can change the level but have to regenerate some of the files as you can see in the Issue https://github.com/yoprogramo/QRcodeDisplay/issues/2#issuecomment-1075726406

Include the code to generate dynamically frames for different levels uses much more flash memory space, so we have not included. If you want to include it (or enhance the code to support more than level 7), please do it and we will include this code in the library.
